name: Rust Deploy

on:
  release:
    types: [created]

jobs:
  tests:
    if: '!github.event.prerelease'
    uses: ./.github/workflows/rust.yml

  deploy_to_crates_dot_io:
    name: Deploy to crates.io
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CRATES_IO_TOKEN }}